package alert

import (
	"context"
	"fmt"
	"net/smtp"
	"strings"
	"time"
	"tisminSRETool/internal/model"
)

type Sender struct {
	resendTimes int
}

func NewEmailSender(resendTimes int) *Sender {
	return &Sender{resendTimes}
}

func (s *Sender) Send(ctx context.Context, alerts []Alert, config model.EmailConfig) error {
	if len(alerts) == 0 {
		return nil
	}

	subject := s.buildSubject(alerts)
	body := s.buildBody(alerts)

	var lastErr error
	for i := 0; i <= s.resendTimes; i++ {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		lastErr = s.sendEmail(subject, body, config)
		if lastErr == nil {
			return nil
		}

		if i < s.resendTimes {
			wait := time.Duration(1<<i) * time.Second
			timer := time.NewTimer(wait)
			select {
			case <-ctx.Done():
				timer.Stop()
				return ctx.Err()
			case <-timer.C:
			}
		}
	}

	return fmt.Errorf("send email failed after %d attempt(s): %w", s.resendTimes+1, lastErr)
}

func (s *Sender) buildSubject(alerts []Alert) string {
	errorCount := 0
	warnCount := 0
	for _, a := range alerts {
		if a.Level == LevelError {
			errorCount++
		} else if a.Level == LevelWarn {
			warnCount++
		}
	}

	host := s.hostFromAlerts(alerts)
	if errorCount > 0 {
		return fmt.Sprintf("[%s] %d Error Alert(s) from tisminSRETool", host, errorCount)
	}
	if warnCount > 0 {
		return fmt.Sprintf("[%s] %d Warning Alert(s) from tisminSRETool", host, warnCount)
	}
	return fmt.Sprintf("[%s] %d Alert(s) from tisminSRETool", host, len(alerts))
}

func (s *Sender) hostFromAlerts(alerts []Alert) string {
	for _, a := range alerts {
		if a.Host != "" {
			return a.Host
		}
	}
	return "unknown"
}

func (s *Sender) buildBody(alerts []Alert) string {
	var buf strings.Builder

	buf.WriteString("Alert Report\n")
	buf.WriteString(strings.Repeat("=", 50))
	buf.WriteString("\n\n")

	for _, a := range alerts {
		buf.WriteString(fmt.Sprintf("[%s] %s\n", a.Level, a.Category))
		buf.WriteString(fmt.Sprintf("  Message: %s\n", a.Message))
		buf.WriteString(fmt.Sprintf("  Host: %s\n", a.Host))
		buf.WriteString(fmt.Sprintf("  Time: %s\n", a.Timestamp.Format(time.RFC3339)))
		buf.WriteString("\n")
	}

	buf.WriteString(strings.Repeat("=", 50))
	buf.WriteString("\n")
	buf.WriteString("Generated by tisminSRETool\n")

	return buf.String()
}

func (s *Sender) sendEmail(subject, body string, config model.EmailConfig) error {
	if config.Host == "" || config.Port <= 0 {
		return fmt.Errorf("invalid smtp host/port")
	}
	if config.From == "" {
		return fmt.Errorf("empty from address")
	}
	if len(config.To) == 0 {
		return fmt.Errorf("empty recipient list")
	}

	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)

	var auth smtp.Auth
	if config.Username != "" || config.Password != "" {
		auth = smtp.PlainAuth("", config.Username, config.Password, config.Host)
	}

	msg := []byte(
		fmt.Sprintf(
			"To: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n%s",
			strings.Join(config.To, ","),
			subject,
			body,
		),
	)

	return smtp.SendMail(addr, auth, config.From, config.To, msg)
}
